using System.Collections.Generic;
using System.Data;
using System.Threading.Tasks;
using Microsoft.Data.SqlClient;
using Microsoft.Extensions.Configuration;

namespace PharmacyManagementSystem.Services
{
	public class SupplierService : ISupplierService
	{
		private readonly string _connectionString;

		public SupplierService(IConfiguration configuration)
		{
			// Retrieves the local connection string configured in MauiProgram.cs
			_connectionString = configuration.GetConnectionString("DefaultConnection")
								?? throw new InvalidOperationException("DefaultConnection string not found.");
		}

		// --- FETCH ALL SUPPLIERS ---
		public async Task<List<Supplier>> GetAllSuppliersAsync()
		{
			var suppliers = new List<Supplier>();
			string sql = "SELECT SupplierId, Name, ContactPerson, Email, Phone, Address, City, Country FROM [Suppliers] WHERE IsDeleted = 0";

			using (var connection = new SqlConnection(_connectionString))
			{
				await connection.OpenAsync();
				using (var command = new SqlCommand(sql, connection))
				{
					using (var reader = await command.ExecuteReaderAsync())
					{
						while (await reader.ReadAsync())
						{
							suppliers.Add(new Supplier
							{
								SupplierId = reader.GetInt32(reader.GetOrdinal("SupplierId")),
								Name = reader.GetString(reader.GetOrdinal("Name")),
								// Use IsDBNull for nullable columns to prevent InvalidCastException
								ContactPerson = reader.IsDBNull(reader.GetOrdinal("ContactPerson")) ? "" : reader.GetString(reader.GetOrdinal("ContactPerson")),
								Email = reader.IsDBNull(reader.GetOrdinal("Email")) ? "" : reader.GetString(reader.GetOrdinal("Email")),
								Phone = reader.IsDBNull(reader.GetOrdinal("Phone")) ? "" : reader.GetString(reader.GetOrdinal("Phone")),
								Address = reader.IsDBNull(reader.GetOrdinal("Address")) ? "" : reader.GetString(reader.GetOrdinal("Address")),
								City = reader.IsDBNull(reader.GetOrdinal("City")) ? "" : reader.GetString(reader.GetOrdinal("City")),
								Country = reader.IsDBNull(reader.GetOrdinal("Country")) ? "" : reader.GetString(reader.GetOrdinal("Country"))
							});
						}
					}
				}
			}
			return suppliers;
		}

		// --- ADD SUPPLIER ---
		public async Task AddSupplierAsync(Supplier supplier)
		{
			// Note: Id is omitted as it should be auto-generated by the database
			string sql = @"INSERT INTO [Suppliers] (Name, ContactPerson, Email, Phone, Address, City, Country) 
                           VALUES (@Name, @ContactPerson, @Email, @Phone, @Address, @City, @Country)";

			using (var connection = new SqlConnection(_connectionString))
			{
				await connection.OpenAsync();
				using (var command = new SqlCommand(sql, connection))
				{
					command.Parameters.AddWithValue("@Name", supplier.Name);
					command.Parameters.AddWithValue("@ContactPerson", supplier.ContactPerson);
					command.Parameters.AddWithValue("@Email", supplier.Email);
					command.Parameters.AddWithValue("@Phone", supplier.Phone);
					command.Parameters.AddWithValue("@Address", supplier.Address);
					command.Parameters.AddWithValue("@City", supplier.City);
					command.Parameters.AddWithValue("@Country", supplier.Country);
					await command.ExecuteNonQueryAsync();
				}
			}
		}

		// --- UPDATE SUPPLIER ---
		public async Task UpdateSupplierAsync(Supplier supplier)
		{
			string sql = @"UPDATE [Suppliers] SET Name = @Name, ContactPerson = @ContactPerson, Email = @Email, 
                           Phone = @Phone, Address = @Address, City = @City, Country = @Country WHERE SupplierId = @SupplierId";

			using (var connection = new SqlConnection(_connectionString))
			{
				await connection.OpenAsync();
				using (var command = new SqlCommand(sql, connection))
				{
					command.Parameters.AddWithValue("@SupplierId", supplier.SupplierId);
					command.Parameters.AddWithValue("@Name", supplier.Name);
					command.Parameters.AddWithValue("@ContactPerson", supplier.ContactPerson);
					command.Parameters.AddWithValue("@Email", supplier.Email);
					command.Parameters.AddWithValue("@Phone", supplier.Phone);
					command.Parameters.AddWithValue("@Address", supplier.Address);
					command.Parameters.AddWithValue("@City", supplier.City);
					command.Parameters.AddWithValue("@Country", supplier.Country);
					await command.ExecuteNonQueryAsync();
				}
			}
		}

		// --- DELETE SUPPLIER ---
		public async Task DeleteSupplierAsync(int Supplierid)
		{
			string sql = "UPDATE [Suppliers] SET IsDeleted = 1 WHERE SupplierId = @SupplierId";

			using (var connection = new SqlConnection(_connectionString))
			{
				await connection.OpenAsync();
				using (var command = new SqlCommand(sql, connection))
				{
					command.Parameters.AddWithValue("@SupplierId", Supplierid);
					await command.ExecuteNonQueryAsync();
				}
			}
		}
	
	
		// ------------------------------------------
		// ARCHIVE / RESTORE
		// ------------------------------------------
		public async Task<List<Supplier>> GetArchivedSuppliersAsync()
		{
			var suppliers = new List<Supplier>();
			string sql = "SELECT SupplierId, Name, ContactPerson, Email, Phone, Address, City, Country FROM [Suppliers] WHERE IsDeleted = 1";

			using (var connection = new SqlConnection(_connectionString))
			{
				await connection.OpenAsync();
				using (var command = new SqlCommand(sql, connection))
				{
					using (var reader = await command.ExecuteReaderAsync())
					{
						while (await reader.ReadAsync())
						{
							suppliers.Add(new Supplier
							{
								SupplierId = reader.GetInt32(reader.GetOrdinal("SupplierId")),
								Name = reader.GetString(reader.GetOrdinal("Name")),
								ContactPerson = reader.IsDBNull(reader.GetOrdinal("ContactPerson")) ? "" : reader.GetString(reader.GetOrdinal("ContactPerson")),
								Email = reader.IsDBNull(reader.GetOrdinal("Email")) ? "" : reader.GetString(reader.GetOrdinal("Email")),
								Phone = reader.IsDBNull(reader.GetOrdinal("Phone")) ? "" : reader.GetString(reader.GetOrdinal("Phone")),
								Address = reader.IsDBNull(reader.GetOrdinal("Address")) ? "" : reader.GetString(reader.GetOrdinal("Address")),
								City = reader.IsDBNull(reader.GetOrdinal("City")) ? "" : reader.GetString(reader.GetOrdinal("City")),
								Country = reader.IsDBNull(reader.GetOrdinal("Country")) ? "" : reader.GetString(reader.GetOrdinal("Country"))
							});
						}
					}
				}
			}
			return suppliers;
		}

		public async Task RestoreSupplierAsync(int id)
		{
			string sql = "UPDATE [Suppliers] SET IsDeleted = 0 WHERE SupplierId = @Id";
			using (var connection = new SqlConnection(_connectionString))
			{
				await connection.OpenAsync();
				using (var command = new SqlCommand(sql, connection))
				{
					command.Parameters.AddWithValue("@Id", id);
					await command.ExecuteNonQueryAsync();
				}
			}
		}
	}
}